spring:
    datasource:
        url: jdbc:mysql://localhost:3306/myChat?useUnicode=true
        username: my_chat
        password: myChat
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
