spring:
    datasource:
        url: jdbc:mysql://localhost:3306/myChat?useUnicode=true
        username: my_chat
        password: myChat
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        hibernate:
            show-sql: true
        properties:
            format_sql: true
