spring:
    datasource:
        url: jdbc:mysql://localhost:3306/myChat?useUnicode=true
        username: my_chat
        password: myChat
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        # properties:
        #     hibernate:
        #         format_sql: true

jwt:
    secret: AnySampleRandomSecretValue
    token-life-span: 
        access: 900000 # 1000 * 60 * 15 millisecond
        refresh: 86400000 # 1000 * 60 * 60 * 24 millisecond

chat:
    life-span: 60000 # 1000 * 60 millisecond
